branch-defaults:
  main:
    environment: ImageFilter-dev
environment-defaults:
  ImageFilter-dev:
    branch: main
    repository: ImageFilter
global:
  application_name: ImageFilter
  branch: main
  default_ec2_keyname: null
  default_platform: Node.js 22 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: ImageFilter
  sc: git
  workspace_type: Application
